<%@ Page Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="Ticketing.Dashboard" %>


<asp:Content ID="Content1" ContentPlaceHolderID="MainContent"
    runat="server">
    <div class="col-100">
<div class="grid">
        
    <asp:GridView ID="Tickets"
        runat="server"
        CellPadding="3"
        GridLines="None"
        HorizontalAlign="Center"
        DataKeyNames="ID"
        OnSelectedIndexChanged ="ClickSelectTicket"
        AllowPaging="True"
        PageSize="20"
        AutoGenerateDeleteButton="True"
        AutoGenerateSelectButton="True" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellSpacing="1">
        <FooterStyle BackColor="#C6C3C6" ForeColor="Black"></FooterStyle>

        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF"></HeaderStyle>
        <PagerStyle HorizontalAlign="Right" BackColor="#C6C3C6" ForeColor="Black"></PagerStyle>

        <RowStyle BackColor="#DEDFDE" ForeColor="Black"></RowStyle>

        <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White"></SelectedRowStyle>

        <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>

        <SortedAscendingHeaderStyle BackColor="#594B9C"></SortedAscendingHeaderStyle>

        <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>

        <SortedDescendingHeaderStyle BackColor="#33276A"></SortedDescendingHeaderStyle>
    </asp:GridView>

    
    

 <div class="grid-button">

      <asp:Button id="BCrea"
        Text="Crea"
        OnClick="CreateTicket"
        runat="server"/>

       
 </div>
  </div>
    
    </asp:Content>    
